#pragma once

#include "AddValueOnHold.h"
#include "Allergy.h"
#include "DamageOnConsume.h"
#include "DamageTakenEnhancer.h"
#include "DropItems.h"
#include "EnhanceTemporaryEffects.h"
#include "HealOnConsume.h"
#include "HealthGainEnhancer.h"
#include "Invulnerable.h"
#include "LifeDrain.h"
#include "Loot.h"
#include "Regen.h"
#include "StartHp.h"
#include "TypeAutoPickup.h"
#include "VenerabilityModifier.h"